import type { LoopTaskSchedulerJobKind } from "../loop/task-family.js";
import type { GovernedPromptId, PromptActionScope, PromptSpec } from "./types.js";

export const ACTION_SCOPE_RANK: Record<PromptActionScope, number> = {
  "read-only": 0,
  "code-change": 1,
  commit: 2,
  "pr-create": 3,
  "auto-merge": 4,
};

export const GOVERNED_PROMPTS: readonly PromptSpec[] = [
  {
    id: "loop.supervisor.main",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "auto-merge",
    evalExpectation: "contract-test",
    description: "Main WorkOrder supervisor prompt and shared execution contract.",
  },
  {
    id: "loop.supervisor.finalization",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "auto-merge",
    evalExpectation: "contract-test",
    description: "Follow-up prompt for missing or unparsable final summaries.",
  },
  {
    id: "loop.supervisor.revision",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "auto-merge",
    evalExpectation: "contract-test",
    description: "Revision prompt for system-gate final summary validation failures.",
  },
  {
    id: "loop.policy.architecture",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["architecture"],
    description: "Single-project architecture health policy.",
  },
  {
    id: "loop.policy.workspace-architecture",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["workspace-architecture"],
    description: "Workspace architecture health policy.",
  },
  {
    id: "loop.policy.bug-fix",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["bug-fix"],
    description: "Confirmed functional, reliability, or security-sensitive bug repair policy.",
  },
  {
    id: "loop.policy.test-coverage",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["test-coverage"],
    description: "Meaningful and maintainable test coverage policy.",
  },
  {
    id: "loop.policy.security-maintenance",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["security-maintenance"],
    description: "Confirmed or plausibly reachable security maintenance policy.",
  },
  {
    id: "loop.policy.harness-auto",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    taskKinds: ["harness-auto"],
    description: "Health-orchestration policy for selecting justified subtasks.",
  },
  {
    id: "loop.policy.opportunity-discovery",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "medium",
    actionScope: "read-only",
    evalExpectation: "contract-test",
    taskKinds: ["opportunity-discovery"],
    description: "Read-only opportunity proposal policy.",
  },
  {
    id: "loop.policy.automation-governance-review",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "workorder-smoke",
    taskKinds: ["automation-governance-review"],
    description: "Self-governance review policy for tmux-claude-bot automation logic.",
  },
  {
    id: "loop.policy.pull-request-review",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "auto-merge",
    evalExpectation: "contract-test",
    taskKinds: ["pull-request-review"],
    description: "Review and merge policy for loop-created pull requests.",
  },
  {
    id: "loop.policy.repository-pull-request-review",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "auto-merge",
    evalExpectation: "contract-test",
    taskKinds: ["repository-pull-request-review"],
    description: "Repository-wide open pull request review policy.",
  },
  {
    id: "loop.policy.repository-pull-request-repair",
    version: 1,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    description: "Bounded repair policy used by repository pull request review.",
  },
  {
    id: "loop.policy.active-delegated-task",
    version: 2,
    owner: "src/core/loop/work-order.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "pr-create",
    evalExpectation: "contract-test",
    description: "Owner-confirmed active delegated task policy.",
  },
  {
    id: "repair.daily-task-audit",
    version: 1,
    owner: "src/core/tasks/task-repair.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    description: "Daily Task Audit self-repair prompt.",
  },
  {
    id: "repair.runtime-guardian",
    version: 1,
    owner: "src/core/runtime-guardian/service.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    description: "Runtime Guardian self-repair prompt.",
  },
  {
    id: "repair.resource-guardian",
    version: 1,
    owner: "src/core/resource-guardian/repair.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    description: "Resource Guardian stable-recovery self-repair prompt.",
  },
  {
    id: "legacy.loop.agent-eval",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "medium",
    actionScope: "read-only",
    evalExpectation: "active-agent-eval",
    legacy: true,
    description: "Legacy command-backed Loop run eval prompt.",
  },
  {
    id: "legacy.loop.agent-task",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "active-agent-eval",
    legacy: true,
    description: "Legacy command-backed agent task execution prompt.",
  },
  {
    id: "legacy.loop.preflight-repair",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    legacy: true,
    description: "Legacy preflight environment repair prompt.",
  },
  {
    id: "legacy.loop.dirty-worktree-recovery",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    legacy: true,
    description: "Legacy dirty-worktree recovery prompt.",
  },
  {
    id: "legacy.loop.verification-recovery",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    legacy: true,
    description: "Legacy verification recovery prompt.",
  },
  {
    id: "legacy.loop.post-commit-dirty-recovery",
    version: 1,
    owner: "src/core/loop/run.ts",
    audience: "active-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "contract-test",
    legacy: true,
    description: "Legacy post-verification commit recovery prompt.",
  },
  {
    id: "opportunity.discussion.single",
    version: 1,
    owner: "src/core/opportunities/view.ts",
    audience: "active-agent",
    riskLevel: "low",
    actionScope: "read-only",
    evalExpectation: "contract-test",
    description: "Single opportunity discussion prompt before implementation.",
  },
  {
    id: "opportunity.discussion.batch",
    version: 1,
    owner: "src/core/opportunities/view.ts",
    audience: "active-agent",
    riskLevel: "low",
    actionScope: "read-only",
    evalExpectation: "contract-test",
    description: "Batch opportunity discussion prompt before implementation.",
  },
  {
    id: "workflow.audit.finder",
    version: 1,
    owner: ".claude/workflows/audit.mjs",
    audience: "operator-agent",
    riskLevel: "medium",
    actionScope: "read-only",
    evalExpectation: "docs-only",
    description: "Audit workflow finding prompt.",
  },
  {
    id: "workflow.audit.verifier",
    version: 1,
    owner: ".claude/workflows/audit.mjs",
    audience: "operator-agent",
    riskLevel: "medium",
    actionScope: "read-only",
    evalExpectation: "docs-only",
    description: "Audit workflow verification prompt.",
  },
  {
    id: "workflow.arch-loop",
    version: 1,
    owner: ".agents/skills/arch-loop/SKILL.md",
    audience: "operator-agent",
    riskLevel: "high",
    actionScope: "commit",
    evalExpectation: "docs-only",
    description: "Operator-triggered architecture health loop skill prompt.",
  },
] as const;

export function governedPromptSpecs(): readonly PromptSpec[] {
  return GOVERNED_PROMPTS;
}

export function governedPromptById(id: GovernedPromptId): PromptSpec {
  const spec = GOVERNED_PROMPTS.find((prompt) => prompt.id === id);
  if (spec === undefined) {
    throw new Error(`Unknown governed prompt: ${id}`);
  }
  return spec;
}

export function governedPromptsForTaskKind(
  taskKind: LoopTaskSchedulerJobKind,
): readonly PromptSpec[] {
  return GOVERNED_PROMPTS.filter((prompt) => prompt.taskKinds?.includes(taskKind));
}

export function actionScopeAtMost(scope: PromptActionScope, maximum: PromptActionScope): boolean {
  return ACTION_SCOPE_RANK[scope] <= ACTION_SCOPE_RANK[maximum];
}
