import * as fs from "node:fs";
import { join } from "node:path";
import { writeFileAtomicSync } from "../shared/utils/atomic-write.js";
import { logger } from "../shared/utils/logger.js";
import { messages } from "./i18n/index.js";
import type { Channel } from "./project-manager.js";
import { claudeConfigDirsInUse } from "./takeover-service.js";
import { snapshotDir } from "./usage-status.js";

/** Absolute path of the generated statusLine script (lives next to the snapshots). */
export function scriptPath(): string {
  return join(snapshotDir(), "statusline.sh");
}

function sidecarPath(configDir: string): string {
  // One per config dir, holding the original statusLine command (wrap mode).
  return join(snapshotDir(), `orig-${configDir.replace(/[^A-Za-z0-9]+/g, "-")}.cmd`);
}

/** The jq block that writes a snapshot — shared by the standalone script and the
 * manual snippet. `<DIR>` is the baked absolute snapshots dir. */
function snapshotJq(dir: string): string {
  return `mkdir -p '${dir}' 2>/dev/null
printf '%s' "$input" | jq -c '{session_id, context_pct:(.context_window.used_percentage//null), five_hour_pct:(.rate_limits.five_hour.used_percentage//null), five_hour_reset:(.rate_limits.five_hour.resets_at//null), seven_day_pct:(.rate_limits.seven_day.used_percentage//null), seven_day_reset:(.rate_limits.seven_day.resets_at//null), updated_at:(now|floor)}' > "${dir}/$(printf '%s' "$input" | jq -r '.session_id // "_"').json" 2>/dev/null`;
}

/** The standalone statusLine script (ASCII / bash-3.2). No arg: prints a minimal
 * status line. Arg = a file holding the original statusLine command → run it and
 * pass its output through (wrap mode). */
export function statuslineScript(dir: string): string {
  return `#!/usr/bin/env bash
# Generated by tmux-claude-bot. Persists a Claude Code usage snapshot for /status.
set -u
input=$(cat)
${snapshotJq(dir)}
if [ "$#" -ge 1 ] && [ -f "$1" ]; then
  orig=$(cat "$1" 2>/dev/null)
  [ -n "$orig" ] && printf '%s' "$input" | sh -c "$orig"
else
  model=$(printf '%s' "$input" | jq -r '.model.display_name // "claude"' 2>/dev/null) || model=claude
  ctx=$(printf '%s' "$input" | jq -r '.context_window.used_percentage // empty' 2>/dev/null) || ctx=''
  if [ -n "$ctx" ]; then printf '%s  ctx %s%%\\n' "$model" "$ctx"; else printf '%s\\n' "$model"; fi
fi
`;
}

/** The block a user pastes into their own statusLine script (assumes it captured
 * stdin into $input, i.e. \`input=$(cat)\`). */
export function manualSnippet(dir: string): string {
  return `# tmux-claude-bot: persist usage snapshot for /status\n${snapshotJq(dir)}`;
}

export type StatusLineState = "clean" | "ours" | "foreign";

/** Classify a settings.json's statusLine relative to our script. */
export function categorizeStatusLine(
  settings: unknown,
  ourPath: string,
): { state: StatusLineState; foreignCmd?: string } {
  const cmd = (settings as { statusLine?: { command?: unknown } } | null)?.statusLine?.command;
  if (typeof cmd !== "string" || cmd.trim() === "") return { state: "clean" };
  if (cmd === ourPath || cmd.startsWith(`${ourPath} `)) return { state: "ours" };
  return { state: "foreign", foreignCmd: cmd };
}

function stamp(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

/** Timestamped backup of settings.json (never clobbers a prior backup). */
function backupSettings(settingsFile: string): string {
  const backup = `${settingsFile}.bak.${stamp()}`;
  fs.copyFileSync(settingsFile, backup);
  logger.info(`[status-install] backed up ${settingsFile} -> ${backup}`);
  return backup;
}

/** Back up (if it exists) then write our statusLine into a dir's settings.json,
 * preserving every other key. Returns the backup path, or null if there was
 * nothing to back up. Crash-safe write. */
function installStatusLine(
  dir: string,
  settings: Record<string, unknown>,
  command: string,
): string | null {
  const settingsFile = join(dir, "settings.json");
  const backup = fs.existsSync(settingsFile) ? backupSettings(settingsFile) : null;
  fs.mkdirSync(dir, { recursive: true });
  settings.statusLine = { type: "command", command };
  writeFileAtomicSync(settingsFile, `${JSON.stringify(settings, null, 2)}\n`);
  return backup;
}

/** Write/refresh the statusLine script (idempotent; content is stable). */
function ensureScript(): void {
  fs.mkdirSync(snapshotDir(), { recursive: true });
  fs.writeFileSync(scriptPath(), statuslineScript(snapshotDir()), { mode: 0o755 });
}

function readSettings(settingsFile: string): Record<string, unknown> {
  try {
    return JSON.parse(fs.readFileSync(settingsFile, "utf8"));
  } catch {
    return {};
  }
}

const errMsg = (e: unknown): string => (e instanceof Error ? e.message : String(e));

export type ForeignAction = "scan" | "overwrite" | "wrap" | "snippet" | "skip";

export interface StatusInstallResult {
  /** Localized report lines for the adapter to render. */
  lines: string[];
  /** True when foreign statusLines were found and (on "scan") need a user choice. */
  foreignPending: boolean;
}

/**
 * Install usage reporting into the running claudes' config dirs. On "scan":
 * auto-install clean dirs, skip ours, and surface foreign ones for a choice.
 * On overwrite/wrap/snippet/skip: apply that to the foreign dirs (clean ones are
 * still installed idempotently). settings.json is backed up before any change.
 */
export async function runStatusInstall(
  channel: Channel,
  action: ForeignAction,
): Promise<StatusInstallResult> {
  const m = messages(channel);
  const dirs = await claudeConfigDirsInUse();
  if (dirs.length === 0) return { lines: [m.statusInstallNoClaude], foreignPending: false };

  ensureScript();
  const lines: string[] = [];
  // Keep each foreign dir's already-read settings so the action loop doesn't re-read.
  const foreign: { dir: string; settings: Record<string, unknown>; cmd: string }[] = [];

  for (const dir of dirs) {
    const settings = readSettings(join(dir, "settings.json"));
    const cat = categorizeStatusLine(settings, scriptPath());
    if (cat.state === "ours") {
      lines.push(m.statusInstallAlready(dir));
    } else if (cat.state === "clean") {
      try {
        installStatusLine(dir, settings, scriptPath());
        lines.push(m.statusInstallInstalled(dir));
      } catch (e) {
        lines.push(m.statusInstallError(dir, errMsg(e)));
      }
    } else {
      foreign.push({ dir, settings, cmd: cat.foreignCmd ?? "" });
    }
  }

  if (foreign.length === 0) return { lines, foreignPending: false };

  if (action === "scan") {
    lines.push(m.statusInstallForeignPrompt(foreign.map((f) => f.dir)));
    return { lines, foreignPending: true };
  }

  for (const { dir, settings, cmd } of foreign) {
    try {
      if (action === "overwrite") {
        lines.push(
          m.statusInstallOverwritten(dir, installStatusLine(dir, settings, scriptPath()) ?? ""),
        );
      } else if (action === "wrap") {
        const sidecar = sidecarPath(dir);
        fs.writeFileSync(sidecar, cmd);
        const backup = installStatusLine(dir, settings, `${scriptPath()} ${sidecar}`);
        lines.push(m.statusInstallWrapped(dir, backup ?? ""));
      } else if (action === "snippet") {
        lines.push(m.statusInstallSnippet(dir, manualSnippet(snapshotDir())));
      } else {
        lines.push(m.statusInstallSkipped(dir));
      }
    } catch (e) {
      lines.push(m.statusInstallError(dir, errMsg(e)));
    }
  }
  return { lines, foreignPending: false };
}
