#!/bin/bash
# Keep the global CLI on the same code surface as the managed service mode.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
MODE="${1:-}"

case "$MODE" in
  "")
    STATE_DIR="$PROJECT_DIR/state"
    CLI_ENTRY="$PROJECT_DIR/dist/cli.js"
    CLI_LOADER=""
    ;;
  --dev)
    STATE_DIR="${TMUX_CLAUDE_BOT_DIR:-$HOME/.tmux-claude-bot}/state"
    CLI_ENTRY="$PROJECT_DIR/src/cli.ts"
    CLI_LOADER="$PROJECT_DIR/node_modules/.bin/tsx"
    ;;
  *)
    echo "usage: $0 [--dev]" >&2
    exit 2
    ;;
esac

NODE_BIN="$(command -v node)"
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

if [ -n "$CLI_LOADER" ]; then
  EXEC_LINE="exec \"$NODE_BIN\" \"$CLI_LOADER\" \"$CLI_ENTRY\" \"\$@\""
else
  EXEC_LINE="exec \"$NODE_BIN\" \"$CLI_ENTRY\" \"\$@\""
fi

cat >"$BIN_DIR/tmux-claude-bot" <<EOF_RUNNER
#!/usr/bin/env bash
set -euo pipefail
# Generated by install-cli-launchers.sh. The CLI and managed service must use
# the same code mode and durable state directory.
export TCB_STATE_DIR="$STATE_DIR"
$EXEC_LINE
EOF_RUNNER
chmod +x "$BIN_DIR/tmux-claude-bot"
ln -sf tmux-claude-bot "$BIN_DIR/tcb"
echo "[install-cli-launchers] installed $MODE launchers in $BIN_DIR"
